#455218　[C#テキスト]1章演習問題
hatta-being/TextC pull request #1
Opened 2023-10-19 08:59 UTC by hatta-being

[C#テキスト]1章演習問題
Chapter1.オブジェクト指向のプログラミングの基礎
1.クラスと構造体
2.値型と参照型
3.静的メンバーと静的クラス
4.名前空間
5.継承
上記について学習しました。

2023-10-26 05:09 UTC, s-morita-being reviewed
研修お疲れ様です。
細かいですが、いくつかコメントしました。

2023-10-26 05:09 UTC, s-morita-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +}
字下げや改行は、コードの構造を視認するのに重要な部分なので、
普段からきちんとそろえる癖をつけるとよいです。

2023-10-26 05:09 UTC, s-morita-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +                return (int)(Price * 0.08);
1 円未満の端数が発生したらどうするのがよいか考えたうえで、
それに合わせて丸めてもらうのがよいかと思います。

2023-10-26 05:09 UTC, s-morita-being commented on 章末問題1/章末問題1/Practice1-3-4/Program1-3-4.cs
> +         wstudent.Name, wstudent.GetAge(), wstudent.ShoolName, wstudent.Grade, wstudent.ClassNumber);
日本語の文章だと先頭を字下げしますが、
コードでは、続きの方を字下げする方が読みやすいと思います。

2023-10-27 01:57 UTC, k-miyahara-being requested changes
解答はおおかたOKと思います！
まずは、コードの見た目をきれいにしてみましょう。

2023-10-27 01:57 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-1-1/Product .cs
> +        public int vPrice { get; set; }
プロパティは接頭辞不要です。
[Wiki > コーディング規約#接頭辞](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#:~:text=%E3%81%AF%E4%BB%98%E3%81%91%E3%81%AA%E3%81%84%E3%80%82-,%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3,-%E3%81%AA%E3%81%97)

他の同様の箇所もあわせて修正をおねがいします

2023-10-27 01:57 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-1-1/Product .cs
> +        }
クラス、プロパティ、コンストラクタ、publicなメソッドにはドキュメントコメント(ヘッダーコメント)を付けてください。
[Wiki > コーディング規約#コメント](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88)

コメントの書き方は、[こちら](https://github.com/kurosu-being/TextC/pull/1#discussion_r1358074333)を参考にしてみてください。

2023-10-27 01:57 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-1-1/Program1-1-1.cs
> +            Product wdorayaki = new Product(98, "どら焼き", 210);
ローカル変数の接頭辞はバッチリです！
接頭辞の次の文字は大文字にするようにしてください。
`wdorayaki` → `wDorayaki`

他の同様の箇所もあわせて修正してください。

2023-10-27 01:57 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-3-1/Person.cs
> +                wage--;
if文は、中の処理が1行しかないときは↓のようにそのまま1行にまとめることができます。
`if (today < Birthday.AddYears(wage)) wage--;`

今回は、条件文が単純かつ中の処理も単純で短いため、1行にまとめたほうが読みやすくなりますが、逆に読みづらくなることもあります。
たとえば、条件文や中の処理が長く複雑な場合、1行の情報量が多くなり読みづらくなります。
また、`else`や`else if`による条件分岐が複数ある場合は、見た目上処理部分がそろっていたほうが読みやすいと感じます。

```
if (条件1) 処理1;
else if (条件2) 処理2;
else 処理3;
```
↓これより
```
if (条件1) {
    処理1;
} else if (条件2) {
    処理2;
} else {
    処理3;
}
```

2023-10-27 01:57 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-3-1/Program1-3-1.cs
> +         wstudent.Name, wstudent.GetAge(), wstudent.ShoolName, wstudent.Grade, wstudent.ClassNumber);
この部分を文字列補間式という方法で書き換えることができます。
[こちら](https://github.com/kurosu-being/TextC/pull/1#discussion_r1358123966)を参考にして書き換えてみてください。

文字列補間式を使うと、`{0}`がどれで、`{1}`がどれで、と見比べる必要がなくなり文字列をストレートに読むことができるのでおすすめです。

2023-10-27 07:14 UTC, hatta-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +}
今のうちに揃える癖をつけておきます。

2023-10-27 07:14 UTC, hatta-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +                return (int)(Price * 0.08);
現在日本では課税売上に係る消費税額、課税仕入に係る消費税額に1円未満の端数があるときは
その端数を切り捨てていることから少数になった場合切り捨てるメソッドを追記しました。

2023-10-27 07:14 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-3-4/Program1-3-4.cs
> +         wstudent.Name, wstudent.GetAge(), wstudent.ShoolName, wstudent.Grade, wstudent.ClassNumber);
字下げするように修正致しました。
その後にコードを書く際のスタート位置は字下げ後に揃えていくものでしょうか？

2023-10-27 07:14 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-1-1/Product .cs
> +        public int vPrice { get; set; }
プロパティの接頭辞を削除致しました。

2023-10-27 07:15 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-1-1/Program1-1-1.cs
> +            Product wdorayaki = new Product(98, "どら焼き", 210);
次の文字を大文字に修正しました。

2023-10-27 07:20 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-3-1/Program1-3-1.cs
> +         wstudent.Name, wstudent.GetAge(), wstudent.ShoolName, wstudent.Grade, wstudent.ClassNumber);
文字列補間式に書き換えてみました。
すると見比べる必要がなくなり読みやすくなったのですが、横長文章となってしまいました。
途中で改行してみたところ問題なく出来るようなのですが、基本的な記述方法はどのかたちになるのでしょうか？

2023-10-27 08:37 UTC, s-morita-being commented on 章末問題1/章末問題1/Practice1-3-4/Program1-3-4.cs
> +         wstudent.Name, wstudent.GetAge(), wstudent.ShoolName, wstudent.Grade, wstudent.ClassNumber);
同じブロック内の文同士は同じインデント(字下げ位置)で開始されるように書くのが一般的です。

C# の文法上はインデントは自由ですが、
人間が読むときに、同じブロック内の文のインデントがそろっている方が
どこからどこまでが一つのブロックか視認しやすいので、そろえるようにしましょう。

分岐やループや関数など、ブロックの入れ子に合わせてインデントされていると、
処理全体の構造/流れを把握しやすくなります。

2023-10-31 07:29 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-3-1/Person.cs
> +                wage--;
1行にまとめてみました。

2023-10-31 07:32 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-1-1/Product .cs
> +        }
自分で見つけられる限りの個所にコメント付け加えてみました。
不足している場合、ご指摘いただけますと幸いです。

2023-11-01 10:12 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-3-1/Program1-3-1.cs
> +         wstudent.Name, wstudent.GetAge(), wstudent.ShoolName, wstudent.Grade, wstudent.ClassNumber);
表示したい文章が長いなら、コードも長くなるのは仕方ないと思います。
見やすくするために、適宜改行を加えるのも良い手と思います。

コーディング規約には文字列について以下のような記述があります。
文字列の連結等の操作のためにStringBuilderというクラスを使うこともありますが、今回の場合は文字列が減ったり増えたりすることがないので、文字列補間か+での連結で十分だと思います。

> ・大量の文字列の連結はStringBuilderを使用する。
使う場面：ループ内で何回も行う連結や、データ由来の文字列やユーザーが入力した文字列が含まれるような文字数の総量が不定の場合。
使わなくてもいい場面：メッセージボックス用など文章量が固定であれば「+」で繋いで構わない。

2023-11-01 10:14 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-1-1/Product .cs
> +        }
プロパティへのコメントはおおかたバッチリですね！

あとは、クラス(Programクラスは除く)、コンストラクタ、publicメソッドも同様にしてみてください。

2023-11-01 10:25 UTC, k-miyahara-being requested changes
コーディング規約の修正漏れなど、もう少し修正してみてください！

2023-11-01 10:25 UTC, k-miyahara-being commented on 章末問題2/章末問題2/ConsoleApp2/Program.cs
1章演習問題とは関係しないものなので、削除しておきましょう。

2023-11-01 10:25 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +
コーディング規約の修正漏れですかね！

2023-11-01 10:25 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +            }
引数のコーディング規約漏れですね。

2023-11-01 10:25 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-3-4/Person.cs
> +        /// <summary>
すべてのクラスは、暗黙的にobjectクラスを継承しています。
`: object`は記述しなくても、Personクラスはobjectクラスを継承するようになっています。
参考：https://ufcpp.net/study/csharp/oo_inherit.html#ctor:~:text=%E3%81%A8%E3%81%84%E3%81%86%E3%81%93%E3%81%A8%E3%81%A7%E3%81%99%E3%80%82-,object%E5%9E%8B,-C%23%20%E3%81%A7%E3%81%AF%E3%80%81%E5%9F%BA%E5%BA%95

2023-11-01 10:25 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-3-4/Person.cs
> +            return wage;
コーディング規約の修正漏れです。
GetAgeメソッドを作るのは問題に指定ありましたっけ？自分でつくった感じですかね？

2023-11-01 10:25 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-3-1/Student.cs
> +        /// <summary>
誤字ですね
`ShoolName`→`SchoolName`

2023-11-01 10:25 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Practice1-3-1/Program1-3-1.cs
> +            };
Studentクラスにコンストラクタを追加して、各プロパティに引数で受け取った値を代入するようにしてみてください。
問1のProductクラスを参考にするとよいです。

2023-11-06 08:08 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-3-1/Program1-3-1.cs
> +            };
問1を参考にコンストラクタ追加してみました。

2023-11-06 08:08 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-3-1/Student.cs
> +        /// <summary>
修正しました。

2023-11-06 08:08 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-3-4/Person.cs
> +            return wage;
Chapter1の中でGetAgeメソッドを使っていて一旦書き写していたそのコードを
書き換えた形で演習問題を解いていたので残っている状態です💦

2023-11-06 08:08 UTC, hatta-being commented on 章末問題1/章末問題1/Practice1-3-4/Person.cs
> +        /// <summary>
わざわざ記述する必要がないのですね🖊

2023-11-06 08:08 UTC, hatta-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +            }
コーディング規約に沿って修正しました。

2023-11-06 08:08 UTC, hatta-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +
再度修正を行いました。

2023-11-13 07:42 UTC, k-miyahara-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +
修正されていない?と思います。

2023-11-14 00:32 UTC, hatta-being commented on 章末問題2/章末問題2/ConsoleApp2/Program.cs
記載漏れしておりました。
消去いたしました。

2023-11-14 00:35 UTC, hatta-being commented on 章末問題1/章末問題1/Program1-1-2/Program1-1-2.cs
> +
ローカル変数 taxAmount → wTaxAmountに修正しました。

2023-11-14 01:00 UTC, k-miyahara-being approved these changes
レビューOKです。

2023-11-14 01:29 UTC, merged