#457409　[C#テキスト]2章演習問題
hatta-being/TextC pull request #2
Opened 2023-11-29 07:52 UTC by hatta-being

2023-12-01 05:02 UTC, k-miyahara-being requested changes

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_1_4/Song_Class.cs
> +    class Song_Class {
クラス名に`_Class`を付けると冗長なのでなくてよいです。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_1_4/Practice2_1_4 .cs
> +            int wAmari1 = wSong1.Length % 60;
コードの中身をあまり理解していない第三者が読んだときもわかるように、変数名を適切に直してみましょう。
以下に気を付けてみてください。
・英単語は特に理由がない限り略さずそのまま書く
・変数が表すものが何かを端的に表す英単語を使用する

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_2/InchConverter.cs
> +    public static class InchConverter {
クラスにコメントを付けましょう。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_2/InchConverter.cs
> +            return vMeter / 0.0254;
メソッドのコメントの書き方がコーディング規約違反です。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/章末問題2/Practice2_1_1.cs
> +            Song_Class wSong3 = new Song_Class("Perfect Night", "LE SSERAFIM", 183);
問題文に「配列Songsに格納」とあるので、これらのSongインスタンスを配列に格納するように実装し直してみてください。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_2/Program.cs
> +                Console.WriteLine("{0}in = {1:0.0000}m", wMeter, wInch);
メートルからインチへの変換なのでFromMeterメソッドを使用するのが正しいと思います。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_2/Program.cs
> +                Console.WriteLine("{0})in = {1:0.0000}m", wInch, wMeter);
for文で使用される`i`のようなループカウンタ変数（ループ変数）の名前は`i`のままでよいです。
コーディング規約の対象外となります。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_3/SalesCounter.cs
> +        private IEnumerable<Sale> _sales;
フィールド変数のコーディング規約違反です。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_3/SalesCounter.cs
> +            foreach (var wLine in wLines) {
変数の型が自明でない場合は`var`ではなく型名を書くようにしてください。
自明とは、`new`するときに右辺に型名が書かれている場合などを言います。

2023-12-01 05:02 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_3/Program.cs
> +            foreach (var wObj in wCalculateSalesPerCategorye) {
変数`wCalculateSalesPerCategorye`はなくて良いかなと思います。
右辺をそのままforeachのinの後に書いてしまえば簡潔になります。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_1_4/Song_Class.cs
> +    class Song_Class {
削除しました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_1_4/Practice2_1_4 .cs
> +            int wAmari1 = wSong1.Length % 60;
略さず端的に表す英単語を使用して修正してみました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_2/InchConverter.cs
> +    public static class InchConverter {
コメント付けました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_2/InchConverter.cs
> +            return vMeter / 0.0254;
コーディング規約を確認し書き方修正しました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/章末問題2/Practice2_1_1.cs
> +            Song_Class wSong3 = new Song_Class("Perfect Night", "LE SSERAFIM", 183);
Songインスタンスを配列に格納し再度実装してみました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_2/Program.cs
> +                Console.WriteLine("{0}in = {1:0.0000}m", wMeter, wInch);
FromMeterに修正しました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_2/Program.cs
> +                Console.WriteLine("{0})in = {1:0.0000}m", wInch, wMeter);
iのままになるよう修正しました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_3/SalesCounter.cs
> +        private IEnumerable<Sale> _sales;
修正しました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_3/SalesCounter.cs
> +            foreach (var wLine in wLines) {
型名に修正しました。

2023-12-04 06:24 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_3/Program.cs
> +            foreach (var wObj in wCalculateSalesPerCategorye) {
そのままforeachのinの後に書き修正しました。

2023-12-06 08:30 UTC, s-morita-being requested changes
研修お疲れ様です。
いくつか指摘しました。

2023-12-06 08:30 UTC, s-morita-being commented on 章末問題2/章末問題2/Practice2_1_4/Practice2_1_4 .cs
> +            Console.WriteLine($"タイトル: {wSong2.Title}　アーティスト名: {wSong2.ArtistName}　演奏時間: {wMinutes2}:{wRemainder2}");
↑だけ `:D2` がないです。

同じ処理を何度も手書きすると間違いのもとですし、
仕様変更等で表示形式を変更することになった場合に、何か所も同じ修正をするのはこれまた間違いのもとです。

同じ処理はメソッドにまとめるなりすると、後が楽になるかと思います。

2023-12-06 08:30 UTC, s-morita-being commented on 章末問題2/章末問題2/Practice2_2_2/Program.cs
> +                Console.WriteLine("{0}in = {1:0.0000}m", i, wInch);
単位の `in` と `m` が逆ですね。

2023-12-06 08:30 UTC, s-morita-being commented on 章末問題2/章末問題2/Practice2_2_3/Program.cs
> +            foreach (var wObj in wSales.GetPerCategorySales()) {
`Dictionary<,>` は列挙順が不定なので、そのままだと人が見づらい出力になってしまうかもしれません。

常にカテゴリの辞書順に出力するなどすると、見やすくなるかと思います。

2023-12-07 08:07 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_1_4/Practice2_1_4 .cs
> +            Console.WriteLine($"タイトル: {wSong2.Title}　アーティスト名: {wSong2.ArtistName}　演奏時間: {wMinutes2}:{wRemainder2}");
メソッドにまとめてみました。

2023-12-07 08:08 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_2/Program.cs
> +                Console.WriteLine("{0}in = {1:0.0000}m", i, wInch);
単位の修正しました。

2023-12-07 08:08 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_3/Program.cs
> +            foreach (var wObj in wSales.GetPerCategorySales()) {
第3章に進んだのちに振り返りこちらを確認する方法が分かりやすいと大平さんより助言をいただきました。
その為学習後、再度修正したいと思います。

2023-12-07 08:32 UTC, s-morita-being requested changes
@hatta-being 
きれいなコードになりましたが、問題の主旨から離れてしまったので、
もう少し検討してもらうとよいです。

2023-12-07 08:32 UTC, s-morita-being commented on 章末問題2/章末問題2/Practice2_1_4/Practice2_1_4 .cs
> +        static void Music(string vTitle, string vArtistName, int vMinutes) {
いいですね。きれいなコードになりました。

が、問題の↓の主旨から離れてしまったのが気になります。
> 配列に格納されたすべてのSongオブジェクト

このメソッドでは `Song` を引数にし、
`Main` では (Practice2_1_1 のように) `Song` の配列つくっておいて、
`foreach` でこのメソッドを呼び出すようにすると、
問題の主旨にも合ってかつきれいなコードにできると思います。

あと、メソッド名ですが、歌の情報を出力する動作なので、 動詞 (+ 目的語) がよいです。

2023-12-08 11:36 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_2/InchConverter.cs
> +            return vMeter / 0.0254;
```
/// <param name="vMeter"></param>
```
↑の部分で、メソッドの説明と同様に引数の説明も書いてください。
↓こんな感じです。
```
/// <param name="vMeter">メートル</param>
```

2023-12-08 11:41 UTC, k-miyahara-being commented on 章末問題2/章末問題2/章末問題2/Practice2_1_1.cs
> +            Song_Class wSong3 = new Song_Class("Perfect Night", "LE SSERAFIM", 183);
OKです！

2023-12-08 11:44 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_3/SalesCounter.cs
> +            foreach (var wLine in wLines) {
foreach文にあるvarも同様です。

2023-12-11 05:56 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_2/InchConverter.cs
> +            return vMeter / 0.0254;
引数の説明追加しました。

2023-12-11 05:56 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_2_3/SalesCounter.cs
> +            foreach (var wLine in wLines) {
修正しました。

29行目以降の//商品別売り上げを求める
で　var wDict = new Dictionary<string, int>();
これは`new‘を使っているのでvarを使うこと可能と思うのですが
 foreach (var wSale in FSales) {
のvarはSaleと型名を書くようにするべきなのでしょうか？

2023-12-11 06:23 UTC, hatta-being commented on 章末問題2/章末問題2/Practice2_1_4/Practice2_1_4 .cs
> +        static void Music(string vTitle, string vArtistName, int vMinutes) {
反映する形で修正を行いました。

2023-12-11 08:05 UTC, k-miyahara-being commented on 章末問題2/章末問題2/Practice2_2_3/SalesCounter.cs
> +            foreach (var wLine in wLines) {
そうですね。
`var`ではなく`Sale`のほうがよいです。

FSalesがなにかのコレクションであることはわかりますが、そのなにかが伝わるように書くことが大切です。
今はFSalesの中身を回しているのである程度型の予測がつくかもしれませんが、
例えば、
`foreach (var wSale in FSales.Select(x => x.Amount)) {` 
のようにメソッドチェーンされているほど`wSale`の型が読み取りづらくなっていきます。

foreachでループごとに変化する変数を定義することは、
いつもの場面で変数を定義するのとなんら変わりないです。

2023-12-11 08:20 UTC, s-morita-being approved these changes
@hatta-being 
修正ありがとうございます。よくなりました。

演習問題なのでここまで止まりですが、 `DisplaySong()` は再利用可能な部品として他の処理にも使えます。
そういう部品がいくつもあると、それらを組み合わて、より高度なプログラムをつくることができるようになります。

2023-12-11 08:20 UTC, s-morita-being commented on 章末問題2/章末問題2/Practice2_1_4/Practice2_1_4 .cs
いいですね。
問題の主旨に沿っていますし、コードも把握しやすくなりました。

2023-12-12 01:30 UTC, merged