Feature/#464428
hatta-being/TextC pull request #3
Opened 2023-12-27 02:47 UTC by hatta-being

[C#テキスト]4章演習問題
Chapter4.基本イディオム
1.初期化に関するイディオム
2.判定と分岐に関するイディオム
3.繰り返しのイディオム
4.条件演算子、null合体演算子によるイディオム
5.プロパティに関するイディオム
6.メソッドに関するイディオム
7.その他のイディオム
上記について学習しました。

2023-12-27 08:23 UTC, ohdaira-being requested changes
コメントしました。
修正、お願いします。
指摘内容や修正方法が分からない場合、いつでも聞いてください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +        new YearMonth(2100, 2)
インデントがずれているので、修正してください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
`YearMonth `クラス内でToString()メソッドオーバーライドしたことで
`WriteLine(wYearMonth );`
とするだけで、今のコードと同じフォーマットで出力できます。
このように修正してみてください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +        }
問題文の回答になっていませんので、`GetFirst21`メソッドの中身を見直してください。
現在、引数の`vYearMonthArray`の最初の要素が`wYearMonth.Is21Century == true`かどうかを比較し、
trueならそのまま最初の要素を返し、falseならnullを返しているようです。
試しに`w21stCenturyData`の最初の要素を21世紀ではないようにしてみると分かりやすいと思います。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            Console.WriteLine(wFound21 != null ? $"{wFound21.Year}年{wFound21.Month}月" : "21世紀のデータはありません");
こちらも上記と同様に
`WriteLine(wYearMonth );`
の形に修正してください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +            int wNewMonth = Month + 1;
プロパティを参照する場合は、`this`を付けるようにしてください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +        }
引数が使われていないので、不要なら削除してください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            var wNextMonthArray = w21stCenturyData.Select(x => x.AddOneMonth(1)).ToArray();
明示的な型を記載してください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            var wSortedArray = wNextMonthArray.OrderBy(x => x.Year).ThenBy(x => x.Month).ToArray();
明示的な型を記載してください。

2023-12-27 08:23 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
`x`という変数名を命名し直してください。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +        new YearMonth(2100, 2)
インデントのずれ修正しました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
書き直してみました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +        }
w21stCenturyDataの要素を21世紀除外して試してみました。
すると最初の条件が真であれば配列内の他の要素を確認せず最初の要素を返してしまいメソッドが終了してしまいました。
そのため見直し修正を行いました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            Console.WriteLine(wFound21 != null ? $"{wFound21.Year}年{wFound21.Month}月" : "21世紀のデータはありません");
書き直してみました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +            int wNewMonth = Month + 1;
thisを付けました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +        }
wNewYear++;を削除しました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            var wNextMonthArray = w21stCenturyData.Select(x => x.AddOneMonth(1)).ToArray();
varをYearMonth[]に修正しました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            var wSortedArray = wNextMonthArray.OrderBy(x => x.Year).ThenBy(x => x.Month).ToArray();
varをYearMonth[]に修正しました。

2024-01-09 04:30 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
wNextMonthAndSortedResultsとしてみました。

2024-01-09 06:39 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +            int wNewMonth = Month + 1;
24行目と48行目でプロパティを参照している個所が治っていませんので、再度修正をお願いします。

2024-01-09 06:45 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +        }
`wNewYear++`を削除するのはgoodです。
不要なコードをコメントアウトするのではなく、削除するようにお願いします。

`AddOneMonth`メソッドは引数を1つ受け取るように書いていますが、
メソッド内の処理を見ると一度も使われていないようです。
不要な引数になりますので、削除するようにお願いします。

2024-01-09 06:52 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +        }
分かってくれたみたいで良かったです！
修正コードは、`foreach`を使って配列をループして、`if`を使って21世紀ではないときはreturnしないようにしてくれましたね。
goodです！

2024-01-09 06:52 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +        new YearMonth(2100, 2)
修正を確認しました。

2024-01-09 06:52 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
修正を確認しました。

2024-01-09 06:53 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            Console.WriteLine(wFound21 != null ? $"{wFound21.Year}年{wFound21.Month}月" : "21世紀のデータはありません");
修正を確認しました。

2024-01-09 06:53 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            var wNextMonthArray = w21stCenturyData.Select(x => x.AddOneMonth(1)).ToArray();
修正を確認しました。

2024-01-09 06:53 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            var wSortedArray = wNextMonthArray.OrderBy(x => x.Year).ThenBy(x => x.Month).ToArray();
修正を確認しました。

2024-01-09 07:16 UTC, odaira1119 commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
口頭で説明しました通りです。
修正お願いします。

【口頭で伝えた内容】
スコープが狭い変数に関しては、抽象度の高い命名でも大丈夫です。
理由はスコープが狭いと、近くにその変数に関するコードがありすぐにどんな変数かが分かるためです。
変数の命名は、コードの読みやすさに関係します。
難しいですが、少しずつ意識していきましょう！

2024-01-12 04:41 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +            int wNewMonth = Month + 1;
再度thisを追加しました。

2024-01-12 04:53 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +        }
wNewYear++をコメントアウトではなく削除しました。

引数int vYearMonthArrayを削除しました。
メソッドを呼び出す箇所が引数を指定していたのでそちらも修正しました。

2024-01-12 04:53 UTC, hatta-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
変数名を変更しました。

2024-01-12 07:37 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +            int wNewMonth = Month + 1;
修正を確認しました。

2024-01-12 07:39 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/YearMonth.cs
> +        }
修正を確認しました。

2024-01-12 07:40 UTC, ohdaira-being commented on 章末問題4/章末問題4/章末問題4/Program.cs
> +            }
修正を確認しました。

2024-01-12 07:51 UTC, merged